package org.bioinfo.cellbase.lib.common.variation;

import java.util.HashSet;
import java.util.Set;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


/**
 * Snp generated by hbm2java
 */
public class Snp implements java.io.Serializable {

	private int snpId;
	private String name;
	private String chromosome;
	private int start;
	private int end;
	private String strand;
	private int mapWeight;
	private String alleleString;
	private String ancestralAllele;
	private String source;
	private String displaySoConsequence;
	private String soConsequenceType;
	private String displayConsequence;
	private String sequence;
//	private Set<SnpXref> snpXrefs = new HashSet<SnpXref>(0);
//	private Set<SnpToTranscript> snpToTranscripts = new HashSet<SnpToTranscript>(
//			0);
	private Set<SnpPhenotypeAnnotation> snpPhenotypeAnnotations = new HashSet<SnpPhenotypeAnnotation>(
			0);
//	private Set<SnpPopulationFrequency> snpPopulationFrequencies = new HashSet<SnpPopulationFrequency>(
//			0);

	public Snp() {
	}

	public Snp(int snpId, String name, String chromosome, int start, int end,
			String strand, int mapWeight, String alleleString,
			String ancestralAllele, String source, String displaySoConsequence,
			String soConsequenceType, String displayConsequence, String sequence) {
		this.snpId = snpId;
		this.name = name;
		this.chromosome = chromosome;
		this.start = start;
		this.end = end;
		this.strand = strand;
		this.mapWeight = mapWeight;
		this.alleleString = alleleString;
		this.ancestralAllele = ancestralAllele;
		this.source = source;
		this.displaySoConsequence = displaySoConsequence;
		this.soConsequenceType = soConsequenceType;
		this.displayConsequence = displayConsequence;
		this.sequence = sequence;
	}

	public Snp(int snpId, String name, String chromosome, int start, int end,
			String strand, int mapWeight, String alleleString,
			String ancestralAllele, String source, String displaySoConsequence,
			String soConsequenceType, String displayConsequence,
			String sequence, Set<SnpPhenotypeAnnotation> snpPhenotypeAnnotations) {
		this.snpId = snpId;
		this.name = name;
		this.chromosome = chromosome;
		this.start = start;
		this.end = end;
		this.strand = strand;
		this.mapWeight = mapWeight;
		this.alleleString = alleleString;
		this.ancestralAllele = ancestralAllele;
		this.source = source;
		this.displaySoConsequence = displaySoConsequence;
		this.soConsequenceType = soConsequenceType;
		this.displayConsequence = displayConsequence;
		this.sequence = sequence;
		this.snpPhenotypeAnnotations = snpPhenotypeAnnotations;
	}

	public int getSnpId() {
		return this.snpId;
	}

	public void setSnpId(int snpId) {
		this.snpId = snpId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getChromosome() {
		return this.chromosome;
	}

	public void setChromosome(String chromosome) {
		this.chromosome = chromosome;
	}

	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

	public String getStrand() {
		return this.strand;
	}

	public void setStrand(String strand) {
		this.strand = strand;
	}

	public int getMapWeight() {
		return this.mapWeight;
	}

	public void setMapWeight(int mapWeight) {
		this.mapWeight = mapWeight;
	}

	public String getAlleleString() {
		return this.alleleString;
	}

	public void setAlleleString(String alleleString) {
		this.alleleString = alleleString;
	}

	public String getAncestralAllele() {
		return this.ancestralAllele;
	}

	public void setAncestralAllele(String ancestralAllele) {
		this.ancestralAllele = ancestralAllele;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getDisplaySoConsequence() {
		return this.displaySoConsequence;
	}

	public void setDisplaySoConsequence(String displaySoConsequence) {
		this.displaySoConsequence = displaySoConsequence;
	}

	public String getSoConsequenceType() {
		return this.soConsequenceType;
	}

	public void setSoConsequenceType(String soConsequenceType) {
		this.soConsequenceType = soConsequenceType;
	}

	public String getDisplayConsequence() {
		return this.displayConsequence;
	}

	public void setDisplayConsequence(String displayConsequence) {
		this.displayConsequence = displayConsequence;
	}

	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}
	
	public Set<SnpPhenotypeAnnotation> getSnpPhenotypeAnnotations() {
		return this.snpPhenotypeAnnotations;
	}

	public void setSnpPhenotypeAnnotations(
			Set<SnpPhenotypeAnnotation> snpPhenotypeAnnotations) {
		this.snpPhenotypeAnnotations = snpPhenotypeAnnotations;
	}
	
/*
	public Set<SnpXref> getSnpXrefs() {
		return this.snpXrefs;
	}

	public void setSnpXrefs(Set<SnpXref> snpXrefs) {
		this.snpXrefs = snpXrefs;
	}

	public Set<SnpToTranscript> getSnpToTranscripts() {
		return this.snpToTranscripts;
	}

	public void setSnpToTranscripts(Set<SnpToTranscript> snpToTranscripts) {
		this.snpToTranscripts = snpToTranscripts;
	}

	public Set<SnpPopulationFrequency> getSnpPopulationFrequencies() {
		return this.snpPopulationFrequencies;
	}

	public void setSnpPopulationFrequencies(
			Set<SnpPopulationFrequency> snpPopulationFrequencies) {
		this.snpPopulationFrequencies = snpPopulationFrequencies;
	}
*/
}
